### ISSUE TITLE
drbd device ntfs filesystem not recognized

### ISSUE THREAD

**Issue by skdia15** [LINBIT/windrbd#13]
hello

I configured drbd resource in nfts file system and resource primary status changed,

and 
I created a database in mssql on the primary disk(f:), 
but It was not recognized as an ntfs file system.

also
cmd> fsutil fsinfo ntfsinfo f:    // command does not recognize it

Is there any way to make the device recognize as ntfs?

data.res configuration
disk                  "e:";		// ntfs disk
meta-disk	"d:";
device		"f:" minor 1;

**Comment by johannesthoma** [comment]
Hi skdia15,

For MS Sql Server to work you have to configure the WinDRBD device as a disk device. This will stack the disk.sys and partmnr.sys drivers (and possibly others depending on your Windows release) over the WinDRBD driver making the device compatible to MS SQL server (and other programs).

To configure WinDRBD for disk device proceed as follows:

drbdadm down <res>

change line device to:

    device minor 1;

(remove the mount point).

clear boot sector of e: device (make sure there is no valueable data on it).

drbdadm up res
drbdadm primary res

open controlpanel - system - partition manager

Once Primary you should see the disk in partition manager. It will prompt for initializing. Select either MBR or GPT. Then add a partition to the disk, format it and assign it the drive letter F:

Then MS SQL server should work as expected.

Please let me know if the procedure works for you,

Best wishes and good luck,

- Johannes

**Comment by skdia15** [comment]
Hi Johannes,

I did what you told me and it’s fine.
Thank you for answer

**Comment by johannesthoma** [comment]
Hi skdia15,

If your issue is solved then please close the ticket (I don't have permission to do so),

Thanks,

- Johannes
