### ISSUE TITLE
Unable to view Existing Data in WinDRBD (on Windows server 2016 ) if Lun Size greater than 1300GB

### ISSUE THREAD

**Issue by chitvan1988** [LINBIT/windrbd#21]
Version:WinDRBD : [install-windrbd-1.0.2-signed.exe]
Steps To Reproduce:
1) Take one Windows Server 2016 OS with one Disk (apart from OS Disk) of Size 1400 GB(issue occurs above size of 1300GB) and one more disk of 5 GB for Metadata
2) Install   windrbd-1.0.2-signed.exe from Linbit Web Site
3) Fill the resource file with the help of mountvol utility.Secondary machine for replication is not required for replication of Issue but values still filled in resource file. Resource File Shall be attached(not of much significance, apart from the fact that external metadata is used)
4) Format the 1400GB Lun  with NTFS and put some data files(even small would do)  in it.
5)Create external  metadata on 5 GB LUN
6) Up the DRBD resource
7) Make the DRBD resource as force primary

Expected Result:  DRBD Volume with NTFS with existing data would be seen with 1400GB Size
 But 
Issue Occurred: DRBD volume is now having multiple partitions with no NTFS.User can no loner access his data from original Windows Machine
[resource.txt](https://github.com/LINBIT/windrbd/files/9167839/resource.txt)

**Comment by johannesthoma** [comment]
Thank you Chitvan for reporting this. I could reproduce the issue. I will do some more research and work on a fix.

Best regards,

- Johannes

**Comment by johannesthoma** [comment]
This should be fixed with WinDRBD 1.1.0-rc4 (and later). Note that you need to specify a drive letter with the device clause as in:

     device "G:" minor 42;
