### ISSUE TITLE
the drbd link has gone

### ISSUE THREAD

**Issue by wangmingxin** [LINBIT/windrbd#3]
which version of drbd is depended by the current windrbd

**Comment by johannesthoma** [comment]
Hi which link are you referring to? If you just want to install windrbd and not build it get a pre built installable EXE from the linbit homepage www.linbit.com under the download tab. The advantage of the pre built binary is that is contains a signed kernel driver so you can load it without putting windows into test mode.

**Comment by wangmingxin** [comment]
the drbd link cloned from https://github.com/LINBIT/windrbd
https://github.com/LINBIT/drbd-9.0/tree/9510e6d8e236d844c6fbf9a57d6fd2a7385c0ea0
Thank you your suggestion.I will try the pre built EXE.

**Comment by johannesthoma** [comment]
Hi yes, thanks for pointing that out. I will fix it in the upcoming 1.0.0-rc2 release sorry
for a delay it is holiday season in Austria (fix will take some weeks). 

Meanwhile you can check out the correct commit manually:

cd drbd       # from windrbd root directory
git checkout fe2b59836bdf1c7c8 # this is the commit this WinDRBD 1.0.0-rc1 is based upon

But in most cases you want to use the installer from the Linbit homepage: Here's the 
link:

https://www.linbit.com/linbit-software-download-page-for-linstor-and-drbd-linux-driver/

Best regards,

- Johannes

**Comment by wangmingxin** [comment]
Thank for your quickly reply and suggestion
